# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "devise_google_authenticator"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christian Frichot"]
  s.date = "2011-11-16"
  s.description = "Devise Google Authenticator Extension"
  s.email = "xntrik@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/devise/checkga_controller.rb",
    "app/controllers/devise/displayqr_controller.rb",
    "app/views/devise/checkga/show.html.erb",
    "app/views/devise/displayqr/show.html.erb",
    "devise_google_authenticator.gemspec",
    "lib/devise_google_authenticatable/controllers/helpers.rb",
    "lib/devise_google_authenticatable/hooks/google_authenticatable.rb",
    "lib/devise_google_authenticatable/models/google_authenticatable.rb",
    "lib/devise_google_authenticatable/orm/active_record.rb",
    "lib/devise_google_authenticatable/patches.rb",
    "lib/devise_google_authenticatable/patches/check_ga.rb",
    "lib/devise_google_authenticatable/patches/display_qr.rb",
    "lib/devise_google_authenticatable/rails.rb",
    "lib/devise_google_authenticatable/routes.rb",
    "lib/devise_google_authenticatable/schema.rb",
    "lib/devise_google_authenticator.rb",
    "test/helper.rb",
    "test/test_devise_google_authenticator.rb"
  ]
  s.homepage = "http://github.com/xntrik/devise_google_authenticator"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Devise Google Authenticator Extension"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<devise>, [">= 0"])
      s.add_runtime_dependency(%q<rotp>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<rotp>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<rotp>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

